dataSetList:
- l0:rainrate
- l1:rgMER_RR
- l1:rgBRZ_RR
rainrate:
  type: RAINRATE
  datatype:
  - dBZ
  RR_METHOD: Z
  MAKE_GLOBAL: 1
rgBRZ_RR:
  type: POINT_MEASUREMENT
  datatype:
  - PROC:RR
  latlon: 1
  truealt: 1
  lat: 46.740753
  lon: 8.06078
  alt: 567.2
  AziTol: 1.0
  EleTol: 5.0
  RngTol: 300.0
  products:
    ts:
      type: POINT_TS
      do_only_final: True
    scores:
      type: COMPARE_SCORES_SENSOR
      varname: "Precipitation:mm"
      sensor: rgage
      sensorid: BRZ
      sensor_scaling: 6
      dir_template: "{%Y-%m-%d}/{sensorid}/"
    sensor:
      type: COMPARE_POINT_SENSOR
      varname: "Precipitation:mm"
      do_only_final: True
      sensor: rgage
      sensorid: BRZ
      sensor_scaling: 6
      dir_template: "{%Y-%m-%d}/{sensorid}/"
      scores:
        - logBias
        - RMSE
        - scatter

rgMER_RR:
  type: POINT_MEASUREMENT
  datatype:
  - PROC:RR
  latlon: 1
  truealt: 1
  lat: 46.732129
  lon: 8.169242
  alt: 588.6
  AziTol: 1.0
  EleTol: 5.0
  RngTol: 300.0
  products:
    ts:
      type: POINT_TS
      do_only_final: True
    scores:
      type: COMPARE_SCORES_SENSOR
      varname: "Precipitation:mm"
      sensor: rgage
      sensorid: MER
      sensor_scaling: 6
      dir_template: "{%Y-%m-%d}/{sensorid}/"
    sensor:
      type: COMPARE_POINT_SENSOR
      varname: "Precipitation:mm"
      do_only_final: True
      sensor: rgage
      sensorid: MER
      sensor_scaling: 6
      dir_template: "{%Y-%m-%d}/{sensorid}/"
      scores:
        - logBias
        - RMSE
        - scatter
