name: read_display_nexrad
datapath: /users/wolfensb/github_repos/pyrad-tests//input_data/read_display_nexrad/KATX/
path_convention: ODIM
loadbasepath: STRING /users/wolfensb/github_repos/pyrad-tests//pyrad_products_test/
loadname: read_display_nexrad
saveimgbasepath: /users/wolfensb/github_repos/pyrad-tests//pyrad_products_test/
s3EndpointWrite: https://eu-central-1.linodeobjects.com/
s3BucketWrite: pyrad-s3-tests
s3PathWrite: Output
imgformat:
- png
configpath: /users/wolfensb/github_repos/pyrad-tests//config/
locationConfigFile: /users/wolfensb/github_repos/pyrad-tests//config/processing/base/read_display_nexrad_loc.yaml
productConfigFile: /users/wolfensb/github_repos/pyrad-tests//config/processing/base/read_display_nexrad_prod.yaml
