name: read_display_cfradialpyrad
loadbasepath: ${PYRAD_TESTS_PATH}/input_data/
loadname: read_display_cfradialpyrad
saveimgbasepath: ${PYRAD_TESTS_PATH}/pyrad_products_test/
imgformat:
- png
s3EndpointWrite: https://eu-central-1.linodeobjects.com/
s3BucketWrite: pyrad-s3-tests
s3PathWrite: Output
configpath: ${PYRAD_TESTS_PATH}/config/
locationConfigFile: ${PYRAD_TESTS_PATH}/config/processing/base/read_display_cfradialpyrad_loc.yaml
productConfigFile: ${PYRAD_TESTS_PATH}/config/processing/base/read_display_cfradialpyrad_prod.yaml
