name: read_display_rainbow
datapath: /users/wolfensb/github_repos/pyrad-tests//input_data/read_display_rainbow/
loadbasepath: /users/wolfensb/github_repos/pyrad-tests//pyrad_products_test/
loadname: read_display_rainbow
s3EndpointWrite: https://eu-central-1.linodeobjects.com/
s3BucketWrite: pyrad-s3-tests
s3PathWrite: Output
saveimgbasepath: /users/wolfensb/github_repos/pyrad-tests//pyrad_products_test/
imgformat:
- png
configpath: /users/wolfensb/github_repos/pyrad-tests//config/
locationConfigFile: /users/wolfensb/github_repos/pyrad-tests//config/processing/base/read_display_rainbow_loc.yaml
productConfigFile: /users/wolfensb/github_repos/pyrad-tests//config/processing/base/read_display_rainbow_prod.yaml
