name: read_process_hydro_cfradial
datapath: ${PYRAD_TESTS_PATH}/input_data/read_process_hydro_cfradial/
loadbasepath: ${PYRAD_TESTS_PATH}/input_data/read_process_hydro_cfradial/
loadname: rad4alp_cosmotemp_PLL
saveimgbasepath: ${PYRAD_TESTS_PATH}/pyrad_products_test/
imgformat: png
s3EndpointWrite: https://s3.pub1.infomaniak.cloud
s3BucketWrite: pyrad-ci
s3PathWrite: Output
configpath: ${PYRAD_TESTS_PATH}/config/
locationConfigFile: ${PYRAD_TESTS_PATH}/config/processing/base/read_process_hydro_cfradial_loc.yaml
productConfigFile: ${PYRAD_TESTS_PATH}/config/processing/base/read_process_hydro_cfradial_prod.yaml
