name: read_display_rainbow
datapath: ${PYRAD_TESTS_PATH}/input_data/read_display_rainbow/
loadbasepath: ${PYRAD_TESTS_PATH}/pyrad_products_test/
loadname: read_display_rainbow
s3EndpointWrite: https://eu-central-1.linodeobjects.com/
s3BucketWrite: pyrad-s3-tests
s3PathWrite: Output
saveimgbasepath: ${PYRAD_TESTS_PATH}/pyrad_products_test/
imgformat:
- png
configpath: ${PYRAD_TESTS_PATH}/config/
locationConfigFile: ${PYRAD_TESTS_PATH}/config/processing/base/read_display_rainbow_loc.yaml
productConfigFile: ${PYRAD_TESTS_PATH}/config/processing/base/read_display_rainbow_prod.yaml
