RadarName: MTCY
RadarRes: L
ScanList:
- ODIM_VOL_HR_MTCY_
ScanPeriod: 5
IconRunFreq: 12
IconForecasted: 24
path_convention: ODIM
DataTypeIDInFiles:
  dBuZ: TH
  ZDR: ZDR
  RhoHV: RHOHV
  uPhiDP: PHIDP
  KDP: KDP
  V: VRADH
  W: WIDTH
  sigma_zh: SIGMA
ppiImageConfig:
  xsize: 10.0
  ysize: 8.0
  xmin: -100.0
  xmax: 100.0
  ymin: -100.0
  ymax: 100.0
rhiImageConfig:
  xsize: 9.0
  ysize: 7.0
  xmin: 0.0
  xmax: 100.0
  ymin: 0.0
  ymax: 8.0
