name: read_display_mfcfradial
datapath: ${PYRAD_TESTS_PATH}/input_data/read_display_mfcfradial/MTCY/
loadbasepath: STRING ${PYRAD_TESTS_PATH}/pyrad_products_test/
loadname: read_display_mfcfradial
saveimgbasepath: ${PYRAD_TESTS_PATH}/pyrad_products_test/
imgformat:
- png
s3EndpointWrite: https://eu-central-1.linodeobjects.com/
s3BucketWrite: pyrad-s3-tests
s3PathWrite: Output
configpath: ${PYRAD_TESTS_PATH}/config/
locationConfigFile: ${PYRAD_TESTS_PATH}/config/processing/mch/read_display_mfcfradial_loc.yaml
productConfigFile: ${PYRAD_TESTS_PATH}/config/processing/mch/read_display_mfcfradial_prod.yaml
