name: read_process_rainbow_psr_sunscan
datapath: ${PYRAD_TESTS_PATH}/input_data/read_process_rainbow_psr_sunscan/
psrpath: ${PYRAD_TESTS_PATH}/input_data/read_process_rainbow_psr_sunscan/PSR/
loadbasepath: ${PYRAD_TESTS_PATH}/pyrad_products_test/
loadname: read_process_rainbow_psr_sunscan
solarfluxpath: /store/msrad/radar/solar_flux/
saveimgbasepath: ${PYRAD_TESTS_PATH}/pyrad_products_test/
s3EndpointWrite: https://eu-central-1.linodeobjects.com/
s3BucketWrite: pyrad-s3-tests
s3PathWrite: Output
imgformat:
- png
configpath: ${PYRAD_TESTS_PATH}/config/
locationConfigFile: ${PYRAD_TESTS_PATH}/config/processing/mch/read_process_rainbow_psr_sunscan_loc.yaml
productConfigFile: ${PYRAD_TESTS_PATH}/config/processing/mch/read_process_rainbow_psr_sunscan_prod.yaml
