name: read_display_metranet_cartesian
datapath: ${PYRAD_TESTS_PATH}/input_data/read_display_metranet_cartesian/
metranet_read_lib: python
loadbasepath: ${PYRAD_TESTS_PATH}/pyrad_products_test/
loadname: read_display_metranet_cartesian
saveimgbasepath: ${PYRAD_TESTS_PATH}/pyrad_products_test/
s3EndpointWrite: https://s3.pub1.infomaniak.cloud
s3BucketWrite: pyrad-ci
s3PathWrite: Output
imgformat:
- png
configpath: ${PYRAD_TESTS_PATH}/config/
locationConfigFile: ${PYRAD_TESTS_PATH}/config/processing/mch/read_display_metranet_cartesian_loc.yaml
productConfigFile: ${PYRAD_TESTS_PATH}/config/processing/mch/read_display_metranet_cartesian_prod.yaml
