name: read_process_rainbow_psr_sunscan
datapath: /users/wolfensb/github_repos/pyrad-tests//input_data/read_process_rainbow_psr_sunscan/
psrpath: /users/wolfensb/github_repos/pyrad-tests//input_data/read_process_rainbow_psr_sunscan/PSR/
loadbasepath: /users/wolfensb/github_repos/pyrad-tests//pyrad_products_test/
loadname: read_process_rainbow_psr_sunscan
solarfluxpath: /store/msrad/radar/solar_flux/
saveimgbasepath: /users/wolfensb/github_repos/pyrad-tests//pyrad_products_test/
s3EndpointWrite: https://eu-central-1.linodeobjects.com/
s3BucketWrite: pyrad-s3-tests
s3PathWrite: Output
imgformat:
- png
configpath: /users/wolfensb/github_repos/pyrad-tests//config/
locationConfigFile: /users/wolfensb/github_repos/pyrad-tests//config/processing/mch/read_process_rainbow_psr_sunscan_loc.yaml
productConfigFile: /users/wolfensb/github_repos/pyrad-tests//config/processing/mch/read_process_rainbow_psr_sunscan_prod.yaml
