name: read_process_maxecho_cfradial
datapath: ${PYRAD_TESTS_PATH}/input_data/read_process_hydro_cfradial/
saveimgbasepath: ${PYRAD_TESTS_PATH}/pyrad_products_test/
imgformat: png
s3EndpointWrite: https://eu-central-1.linodeobjects.com/
s3BucketWrite: pyrad-s3-tests
s3PathWrite: Output
configpath: ${PYRAD_TESTS_PATH}/config/
locationConfigFile: ${PYRAD_TESTS_PATH}/config/processing/mch/read_process_maxecho_cfradial_loc.yaml
productConfigFile: ${PYRAD_TESTS_PATH}/config/processing/mch/read_process_maxecho_cfradial_prod.yaml
